#!/user/bin/env python3
# -*- coding: utf-8 -*-


import requests,time
from bs4 import BeautifulSoup


def crawlproxy(url):
	headers={
		'Host':'www.xicidaili.com',
		'Connection':'keep-alive',
		'Cache-Control':'max-age=0',
		'Upgrade-Insecure-Requests':'1',
		'User-Agent':'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 '
		             'Safari/537.36',
		'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
		'Referer':'http://www.xicidaili.com/',
		'Accept-Encoding':'gzip, deflate, sdch',
		'Accept-Language':'zh-CN,zh;q=0.8',
		'If-None-Match':'W/"ffb6537b6df8d29ec3c8eff56ad4f6ab"'}
	# cookies={
	#     '_free_proxy_session'
	#
	# '':'BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTI0OTJlN2JmODhiZDQ3YjM0NjBlODhhODk0Zjg5OWE3BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMW5hZTFSSy9BM01wdXJFNHF3MFoxNXV5R1AwZGhZSVdJaFd4Q1ZqRGVmUFk9BjsARg%3D%3D--9b53462a86200fd54193e2c7da6a4d04d953c014',
	#     'Hm_lvt_0cf76c77469e965d2957f0553e6ecf59':'1491813781',
	#     'Hm_lpvt_0cf76c77469e965d2957f0553e6ecf59':'1491814369'}

	r=requests.get(url,headers=headers)
	html=BeautifulSoup(r.content,'lxml')
	proxylist=[]
	for proxyinfo in html.find_all('tr'):
		try:
			info=(proxyinfo.find_all('td')[1].text+
			      ':'+
			      proxyinfo.find_all('td')[2].text+
			      '@'+
			      proxyinfo.find_all('td')[5].text+
			      '$未验证#'+
			      proxyinfo.find_all('td')[3].find('a').text+
			      proxyinfo.find_all('td')[4].text)
			print(info)
			proxylist.append(info)
		except:
			pass
	print('共收录代理信息:%s条!%s'%(len(proxylist),url))
	return proxylist


urllist=['http://www.xicidaili.com/nn/','http://www.xicidaili.com/nt/','http://www.xicidaili.com/wn/',
         'http://www.xicidaili.com/wt/']

if __name__=='__main__':

	with open('D://proxyinfo.txt','w+') as filecreate:
		filecreate.write('')
		filecreate.close()

	for url in urllist:
		time.sleep(1)
		with open('D://proxyinfo.txt','a') as filewrite:
			for n in crawlproxy(url):
				filewrite.write(n+'\n')
			filewrite.close()
		print('done')
